# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  name: 'Noteworx'
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image

  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          set -x
          pwd
          ls -lrt
          echo 'Hello world'
          # docker rmi -f $(docker images -q) || true
          docker rmi -f $(docker images | grep murali90102 | awk '{print $3}')
          docker system prune -f
          # docker build -f dockerfiles/Dockerfile.be -t murali90102/noteworkxbe:$(tag) .
          # docker build -f dockerfiles/Dockerfile.fe -t murali90102/noteworkxfe:$(tag) .
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          set -x

          docker build -f dockerfiles/Dockerfile.be -t murali90102/noteworkxbe:$(tag) .
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          docker build -f dockerfiles/Dockerfile.fe -t murali90102/noteworkxfe:$(tag) .
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'murali90102/noteworkxbe'
        command: 'push'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'murali90102/noteworkxfe'
        command: 'push'
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'AKS-networx'
        command: 'get'
        arguments: 'pods,svc'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          ## Update Image Tag
          set -x
          sed -i -e "s/noteworkxfe:TAG/noteworkxfe:$(tag)/1" -e "s/noteworkxbe:TAG/noteworkxbe:$(tag)/1" K8/All-Deployment.yaml
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'AKS-networx'
        command: 'apply'
        arguments: '-f K8/All-Deployment.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        forceUpdate: false
        outputFormat: 'none'
        

    
